export const drops = [
  {
    id: 1,
    name: "Nganya Noir",
    vibe: "party",
    price: 4500,
    mood: "This cab hits like a Sewer Sydaa hook – loud berries, louder nights.",
    badge: "Flash Deal",
  },
  {
    id: 2,
    name: "Gengetone Gin",
    vibe: "party",
    price: 5200,
    mood: "Juniper, citrus, and peppery swagger for rooftop sessions.",
    badge: "Top Drop",
  },
  {
    id: 3,
    name: "Arbantone Aged Rum",
    vibe: "smooth",
    price: 6800,
    mood: "Molasses, smoke, and buttery bars – pace yourself.",
    badge: "Limited",
  },
  {
    id: 4,
    name: "Rong Rendé Sake",
    vibe: "collectors",
    price: 9800,
    mood: "Silky umami finish curated for lyricists and tastemakers.",
    badge: "Exclusive",
  },
  {
    id: 5,
    name: "Cypher Citrus Vodka",
    vibe: "party",
    price: 3600,
    mood: "Neon grapefruit profile for late-night DJ sets.",
    badge: "Hot Zone",
  },
  {
    id: 6,
    name: "Upper Hill Single Malt",
    vibe: "smooth",
    price: 12500,
    mood: "12-year-aged oak swagger with honey drizzle.",
    badge: "Premium",
  },
  {
    id: 7,
    name: "Eastlands Aperitivo",
    vibe: "collectors",
    price: 5400,
    mood: "Bitter orange & tamarind, made for sunsets over Umoja.",
    badge: "Collab",
  },
  {
    id: 8,
    name: "Buru Buru Bubbles",
    vibe: "party",
    price: 4200,
    mood: "Kenyan rosé bubbles for dance floor proposals.",
    badge: "Limited",
  },
];

